name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-10, clang++-12]
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libfreetype-dev ${{ matrix.compiler }}
    - name: configure
      run: mkdir ${{ matrix.configuration }} && cd ${{ matrix.configuration }} && cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D CMAKE_CXX_COMPILER=${{ matrix.compiler }} ..
    - name: build
      run: cmake --build ${{ matrix.configuration }} -j $(nproc --all)
